{
    'save_episode_num': 200,
    'lr_start': 0.001,
    'lr_end': 0.0001,
    'lr_decay': 20,
    'epoch': 50,

    'total_episode_num': 2000,
    'batch_size': 8,
    'gamma': 0.999,
    'eps_start': 0.9,
    'eps_end': 0.05,
    'eps_decay': 20,
    'target_update': 2,
    'save_every': 10,
    'save_model_path': 'model/model.pth'
}
